name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build and run tests
      run: ./gradlew build connectedCheck
      working-directory: android-questions/WordyByFarber

    - name: Report Coverage
      if: always()
      run: ./gradlew jacocoTestReport
      working-directory: android-questions/WordyByFarber

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: android-questions/WordyByFarber/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

